flu:
	pdflatex presentation
	#bibtex presentation
	#bibtex presentation
	pdflatex presentation
	#pdflatex presentation
	#pdflatex presentation
clean:
	rm -f *.log *.synctex.gz *.fdb*
	rm -f *.aux *.bbl *.blg *.dvi
	rm -f *.ps  *.out *.bak
	rm -f *.nav  *.snm *.toc
