flu:
	pdflatex ltexpprt
	bibtex ltexpprt
	bibtex ltexpprt
	pdflatex ltexpprt
	pdflatex ltexpprt
	pdflatex ltexpprt
clean:
	rm -f *.log *.synctex.gz *.fdb*
	rm -f *.aux *.bbl *.blg *.dvi
	rm -f *.ps  *.out *.bak
